# Generated by Django 5.2.10 on 2026-01-15 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=128)),
                (
                    "ceeb_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "external_average_gpa",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "external_average_act_score",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "external_average_sat_score",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "SCED_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=12
                    ),
                ),
                ("course_name", models.CharField(db_index=True, max_length=128)),
                ("course_description", models.TextField(blank=True, null=True)),
                ("subject_area", models.CharField(max_length=128)),
                ("AP_course", models.BooleanField(default=False)),
                ("IB_course", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=128)),
                ("county", models.CharField(blank=True, default="", max_length=128)),
                ("zip_code", models.CharField(blank=True, default="", max_length=128)),
                (
                    "external_average_gpa",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "external_average_act_score",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "external_average_sat_score",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HighSchool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=128)),
                (
                    "external_average_gpa",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "external_average_act_score",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "external_average_sat_score",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="high_schools",
                        to="core.district",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("gender", models.CharField(blank=True, default="", max_length=128)),
                ("ethnicity", models.CharField(blank=True, default="", max_length=128)),
                (
                    "sexual_orientation",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "disability",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("low_income", models.BooleanField(default=False)),
                ("GPA", models.FloatField(blank=True, default=0.0, null=True)),
                ("ACT_score", models.IntegerField(blank=True, null=True)),
                ("SAT_score", models.IntegerField(blank=True, null=True)),
                ("first_generation_student", models.BooleanField(default=False)),
                (
                    "intended_major",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "grade_level",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "high_school_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="core.highschool",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(blank=True, default="", max_length=2)),
                ("semester", models.CharField(blank=True, default="", max_length=128)),
                ("year", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="core.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="core.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="student",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                through="core.Enrollment",
                to="core.student",
            ),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_result",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "application_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("attending", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "legacy_status",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.college",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.student",
                    ),
                ),
            ],
        ),
    ]
