# Generated by Django 5.2.10 on 2026-01-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="college",
            name="name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
