# Generated by Django 5.2.10 on 2026-01-16 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_college_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="high_school_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="core.highschool",
            ),
        ),
    ]
