# Generated by Django 5.2.10 on 2026-01-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_student_high_school_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="GPA",
            new_name="gpa",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="high_school_name",
            new_name="high_school",
        ),
        migrations.AddField(
            model_name="district",
            name="internal_average_act_score",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="internal_average_gpa",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="internal_average_sat_score",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="highschool",
            name="internal_average_act_score",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="highschool",
            name="internal_average_gpa",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="highschool",
            name="internal_average_sat_score",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="district",
            name="external_average_act_score",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="district",
            name="external_average_sat_score",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="highschool",
            name="external_average_act_score",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="highschool",
            name="external_average_sat_score",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
